name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  upload-dist-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate dist assets
        shell: bash
        run: |
          test -f dist/go_selfupdate_windows_amd64.exe

      - name: Upload asset to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/go_selfupdate_windows_amd64.exe
